import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Space_Grotesk, Poppins } from 'next/font/google'
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import FooterNew from "@/components/FooterNew";

const spaceGrotesk = Space_Grotesk({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-display'
})

const poppins = Poppins({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
    variable: '--font-body'
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full uppercase flex flex-col">
<Navbar />
        <Container>
        {children}
        </Container>
      <FooterNew />

      </body>
    </html>
  );
}
